rng.settings:
  type: config_entity
  label: 'RNG settings'
  mapping:
    identity_types:
      type: sequence
      label: 'Identity types'
      sequence:
        type: string

rng.registration_type.*:
  type: config_entity
  label: 'Registration type'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'

rng.registrant_type.*:
  type: config_entity
  label: 'Registrant type'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'

rng.event_type.*.*:
  type: config_entity
  label: 'Event bundle settings'
  mapping:
    id:
      type: string
      label: 'ID'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    mirror_operation_to_event_manage:
      type: string
      label: 'Mirrors another operation grant from the event to event manage.'
    custom_rules:
      type: boolean
      label: 'Allow event managers to customise default rules.'
    default_registrant:
      type: string
      label: 'Registrant type for new registrants associated with this event type.'
    people_types:
      type: sequence
      label: 'Types of people types allowed to be associated with this event type.'
      sequence:
        type: rng_event_type_people_type

condition.plugin.rng_user_role:
  type: condition.plugin.user_role

condition.plugin.rng_registration_identity:
  type: condition.plugin

condition.plugin.rng_event_operation:
  type: condition.plugin
  mapping:
    operations:
      type: mapping
      mapping:
        'manage event':
          type: boolean
          label: 'Manage event'

action.configuration.registration_operations:
  type: mapping
  label: 'Set registration operation access configuration.'
  mapping:
    operations:
      type: mapping
      mapping:
        create:
          type: boolean
          label: 'Create'
        view:
          type: boolean
          label: 'View'
        update:
          type: boolean
          label: 'Update'
        delete:
          type: boolean
          label: 'Delete'

rng.rule.*.*.*:
  type: config_entity
  label: 'A collection of default rules'
  mapping:
    id:
      type: string
      label: 'ID'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    machine_name:
      type: string
      label: 'Machine name'
    trigger:
      type: string
      label: 'Trigger'
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Condition'
    actions:
      type: sequence
      label: 'Actions'
      sequence:
        label: 'Action'
        type: rng_action.plugin

user.role.*.third_party.rng:
  type: mapping
  mapping:
    condition_rng_role:
      type: boolean
      label: 'Expose this rule to RNG role condition plugin'
